import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel: string) => readFileSync(path.join(root, rel), 'utf8');

// ---------------------------------------------------------------------------
// W2 — bundled Tailwind (no CDN JIT compiler in production)
// ---------------------------------------------------------------------------

test('index.html does not load the Tailwind CDN <script> (W2)', () => {
  const html = read('index.html');
  // The render-blocking in-browser JIT compiler must be gone; only the bundled
  // stylesheet (emitted by Vite/PostCSS) styles production.
  assert.doesNotMatch(html, /<script[^>]+src=["']https:\/\/cdn\.tailwindcss\.com/);
  assert.doesNotMatch(html, /tailwind\.config\s*=/);
});

test('the Tailwind toolchain is committed (config + entry CSS) (W2)', () => {
  assert.doesNotThrow(() => read('tailwind.config.js'), 'tailwind.config.js present');
  assert.doesNotThrow(() => read('postcss.config.js'), 'postcss.config.js present');
  const css = read('index.css');
  assert.match(css, /@tailwind base;/);
  assert.match(css, /@tailwind utilities;/);
});

test('index.tsx imports the bundled stylesheet (W2)', () => {
  assert.match(read('index.tsx'), /import ['"]\.\/index\.css['"]/);
});

// ---------------------------------------------------------------------------
// W13 — theme-color meta + manifest identity/colors
// ---------------------------------------------------------------------------

const BODY_BG = '#020617';

test('index.html declares a theme-color meta matching the served body bg (W13)', () => {
  const html = read('index.html');
  const m = html.match(/<meta\s+name=["']theme-color["']\s+content=["']([^"']+)["']/i);
  assert.ok(m, 'theme-color meta present');
  assert.equal(m![1].toLowerCase(), BODY_BG);
});

test('site.webmanifest uses the Dan-spoke identity name, not "Daniel Mercede" (W13)', () => {
  const manifest = JSON.parse(read('public/site.webmanifest'));
  assert.equal(manifest.name, 'Dan Mercede');
});

test('site.webmanifest theme/background match the served body bg (W13)', () => {
  const manifest = JSON.parse(read('public/site.webmanifest'));
  assert.equal(manifest.theme_color.toLowerCase(), BODY_BG);
  assert.equal(manifest.background_color.toLowerCase(), BODY_BG);
});

// ---------------------------------------------------------------------------
// W9 — sitemap lastmod reflects REAL change, never an every-build auto-bump
// ---------------------------------------------------------------------------

test('sitemap lastmods are valid YYYY-MM-DD dates, none in the future (W9)', () => {
  const xml = read('public/sitemap.xml');
  const mods = [...xml.matchAll(/<lastmod>([^<]+)<\/lastmod>/g)].map((m) => m[1].trim());
  assert.ok(mods.length > 0, 'sitemap has lastmod entries');
  const today = new Date().toISOString().slice(0, 10);
  for (const d of mods) {
    assert.match(d, /^\d{4}-\d{2}-\d{2}$/, `lastmod ${d} must be YYYY-MM-DD`);
    assert.ok(!Number.isNaN(Date.parse(d)), `lastmod ${d} must be a real date`);
    assert.ok(d <= today, `lastmod ${d} must not be in the future (no fabricated freshness)`);
  }
});

test('sitemap.xml is a static committed file, not regenerated by build (W9)', () => {
  // Guards the W9 constraint: no build step rewrites lastmod every run. If a
  // generator is ever added it must derive lastmod from real content change;
  // until then the file is hand-maintained and the build must not touch it.
  const pkg = JSON.parse(read('package.json'));
  const buildScript = String(pkg.scripts.build || '');
  assert.doesNotMatch(buildScript, /sitemap/i, 'build script must not regenerate the sitemap');
});
