import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel: string) => readFileSync(path.join(root, rel), 'utf8');

// ---------------------------------------------------------------------------
// W2 — bundled Tailwind (no CDN JIT compiler in production)
// ---------------------------------------------------------------------------

test('index.html does not load the Tailwind CDN <script> (W2)', () => {
  const html = read('index.html');
  // The render-blocking in-browser JIT compiler must be gone; only the bundled
  // stylesheet (emitted by Vite/PostCSS) styles production.
  assert.doesNotMatch(html, /<script[^>]+src=["']https:\/\/cdn\.tailwindcss\.com/);
  assert.doesNotMatch(html, /tailwind\.config\s*=/);
});

test('the Tailwind toolchain is committed (config + entry CSS) (W2)', () => {
  assert.doesNotThrow(() => read('tailwind.config.js'), 'tailwind.config.js present');
  assert.doesNotThrow(() => read('postcss.config.js'), 'postcss.config.js present');
  const css = read('index.css');
  assert.match(css, /@tailwind base;/);
  assert.match(css, /@tailwind utilities;/);
});

test('index.tsx imports the bundled stylesheet (W2)', () => {
  assert.match(read('index.tsx'), /import ['"]\.\/index\.css['"]/);
});

// ---------------------------------------------------------------------------
// W13 — theme-color meta + manifest identity/colors
// ---------------------------------------------------------------------------

const BODY_BG = '#020617';

test('index.html declares a theme-color meta matching the served body bg (W13)', () => {
  const html = read('index.html');
  const m = html.match(/<meta\s+name=["']theme-color["']\s+content=["']([^"']+)["']/i);
  assert.ok(m, 'theme-color meta present');
  assert.equal(m![1].toLowerCase(), BODY_BG);
});

test('site.webmanifest uses the Dan-spoke identity name, not "Daniel Mercede" (W13)', () => {
  const manifest = JSON.parse(read('public/site.webmanifest'));
  assert.equal(manifest.name, 'Dan Mercede');
});

test('site.webmanifest theme/background match the served body bg (W13)', () => {
  const manifest = JSON.parse(read('public/site.webmanifest'));
  assert.equal(manifest.theme_color.toLowerCase(), BODY_BG);
  assert.equal(manifest.background_color.toLowerCase(), BODY_BG);
});

// ---------------------------------------------------------------------------
// W9 — sitemap lastmod reflects REAL change, never an every-build auto-bump
// ---------------------------------------------------------------------------

test('sitemap lastmods are valid YYYY-MM-DD dates, not fabricated-future (W9)', () => {
  const xml = read('public/sitemap.xml');
  const mods = [...xml.matchAll(/<lastmod>([^<]+)<\/lastmod>/g)].map((m) => m[1].trim());
  assert.ok(mods.length > 0, 'sitemap has lastmod entries');
  // Anti-fabrication guard: a lastmod must be a real calendar date and not
  // claim freshness from a far-future date. A small slack tolerates CI clock
  // skew / timezone so the suite is not fragile around the stamp date itself.
  const slackDays = 2;
  const maxMs = Date.now() + slackDays * 24 * 60 * 60 * 1000;
  for (const d of mods) {
    assert.match(d, /^\d{4}-\d{2}-\d{2}$/, `lastmod ${d} must be YYYY-MM-DD`);
    const parsed = new Date(`${d}T00:00:00Z`);
    assert.ok(!Number.isNaN(parsed.getTime()), `lastmod ${d} must be a real date`);
    // Date.parse/new Date normalizes overflow dates (2026-02-31 -> 2026-03-03),
    // so a format-valid but non-calendar date would otherwise slip through.
    // Round-trip the parsed value back to YYYY-MM-DD and require it to match.
    assert.equal(
      parsed.toISOString().slice(0, 10),
      d,
      `lastmod ${d} must be a real calendar date (no overflow normalization)`,
    );
    assert.ok(parsed.getTime() <= maxMs, `lastmod ${d} must not be fabricated-future (no inflated freshness)`);
  }
});

test('sitemap.xml is a static committed file, not regenerated by build (W9)', () => {
  // Guards the W9 constraint: no build step rewrites lastmod every run. If a
  // generator is ever added it must derive lastmod from real content change;
  // until then the file is hand-maintained and the build must not touch it.
  const pkg = JSON.parse(read('package.json'));
  const buildScript = String(pkg.scripts.build || '');
  assert.doesNotMatch(buildScript, /sitemap/i, 'build script must not regenerate the sitemap');
});

// ---------------------------------------------------------------------------
// W3 — /assets immutable cache is scoped to content-hashed static assets only.
// Stable-named human download artifacts (proof PDFs/DOCX/PPTX, case-study docs)
// also live under /assets/; year-caching them `immutable` means a corrected
// artifact under the SAME filename never revalidates for a year. The immutable
// rule must match Vite-hashed asset extensions and NOT document extensions.
// ---------------------------------------------------------------------------

type VercelHeaderRule = {
  source: string;
  headers: { key: string; value: string }[];
};

/**
 * Resolve the Cache-Control value Vercel would apply to a path: first matching
 * `headers[].source` rule wins, sources are anchored full-path regexes. Returns
 * undefined when no rule matches (Vercel default caching applies).
 */
function cacheControlFor(rules: VercelHeaderRule[], pathName: string): string | undefined {
  return firstMatchHeaders(rules, pathName)['cache-control'];
}

/**
 * Resolve the full header map Vercel would apply to a path under first-match
 * semantics (the branch's own helper models Vercel headers as first-match wins):
 * the FIRST rule whose `source` matches supplies the headers; later rules do not
 * merge. Keys are lower-cased. Empty object when no rule matches.
 */
function firstMatchHeaders(rules: VercelHeaderRule[], pathName: string): Record<string, string> {
  for (const rule of rules) {
    // host-conditional preview rules etc. carry a `has`; ignore those here.
    if ((rule as { has?: unknown }).has) continue;
    const re = new RegExp(`^${rule.source}$`);
    if (re.test(pathName)) {
      const out: Record<string, string> = {};
      for (const h of rule.headers) out[h.key.toLowerCase()] = h.value;
      return out;
    }
  }
  return {};
}

test('vercel.json immutable /assets rule caches a hashed bundle but NOT a human doc (W3)', () => {
  const vercel = JSON.parse(read('vercel.json')) as { headers: VercelHeaderRule[] };
  const rules = vercel.headers;

  // A real Vite content-hashed bundle path: immutable year cache is correct
  // (the hash changes when content changes, so the old URL is never reused).
  const hashedBundle = '/assets/index-CHQzmtiG.js';
  const bundleCC = cacheControlFor(rules, hashedBundle);
  assert.ok(bundleCC, `${hashedBundle} must match a Cache-Control rule`);
  assert.match(
    bundleCC!,
    /\bimmutable\b/,
    `hashed bundle ${hashedBundle} must keep the immutable year cache`,
  );
  assert.match(bundleCC!, /max-age=31536000/, 'hashed bundle keeps the 1-year max-age');

  // A real stable-named human download artifact (from constants.ts, linked via
  // App.tsx download anchors): must NOT be immutable, or a same-filename
  // correction would be year-cached and never revalidate.
  const docPath = '/assets/Executive_Deck.pdf';
  const docCC = cacheControlFor(rules, docPath);
  assert.doesNotMatch(
    docCC ?? '',
    /\bimmutable\b/,
    `human download ${docPath} must NOT be immutable (same-filename corrections must revalidate)`,
  );
  assert.doesNotMatch(
    docCC ?? '',
    /max-age=31536000/,
    `human download ${docPath} must NOT carry the 1-year max-age`,
  );

  // A second document extension to lock the scoping (DOCX case-study).
  const docxPath = '/assets/Reference_Architecture_Healthcare.docx';
  assert.doesNotMatch(
    cacheControlFor(rules, docxPath) ?? '',
    /\bimmutable\b/,
    `${docxPath} must NOT be immutable`,
  );
});

test('every /assets document artifact referenced in constants.ts is NOT immutable (W3)', () => {
  const vercel = JSON.parse(read('vercel.json')) as { headers: VercelHeaderRule[] };
  const constants = read('constants.ts');
  const docPaths = [...constants.matchAll(/filePath:\s*["'](\/assets\/[^"']+)["']/g)].map(
    (m) => m[1],
  );
  assert.ok(docPaths.length > 0, 'constants.ts must reference at least one /assets download');
  for (const p of docPaths) {
    const cc = cacheControlFor(vercel.headers, p) ?? '';
    assert.doesNotMatch(cc, /\bimmutable\b/, `${p} (human download) must not be immutable`);
  }
});

test('runtime-governance diagram SVG keeps its image/svg+xml Content-Type under the broad rule (W3)', () => {
  // The broad hashed-asset rule also matches `*.svg`, so under first-match
  // semantics it could shadow the diagram-specific rule that adds
  // `Content-Type: image/svg+xml`. The diagram rules must therefore sit BEFORE
  // the broad rule so a real diagram SVG still resolves to the explicit
  // content-type rule — and still keeps the immutable cache.
  const vercel = JSON.parse(read('vercel.json')) as { headers: VercelHeaderRule[] };
  const diagramSvg = '/assets/runtime-governance/diagrams/control-plane-architecture/x-v1.svg';
  const headers = firstMatchHeaders(vercel.headers, diagramSvg);
  assert.equal(
    headers['content-type'],
    'image/svg+xml',
    'diagram SVG must keep its explicit image/svg+xml Content-Type (not shadowed by the broad /assets rule)',
  );
  assert.match(
    headers['cache-control'] ?? '',
    /\bimmutable\b/,
    'diagram SVG keeps the immutable year cache',
  );
});
