// Compile content/guides/*.md (frontmatter + markdown body) into a committed
// constants.guides.generated.ts bundle exporting GUIDES: Guide[].
//
// Why a generator (vs hand-writing the array in constants.ts like WORKS): a guide
// body is multi-thousand-word markdown full of backticks and ${...} sequences,
// which cannot live as a clean TS literal. JSON.stringify embeds it safely as a
// double-quoted string (no template-literal interpolation, no escaping hazards),
// exactly as constants.generated.ts stores THOUGHTS bodies.
//
// This is STATIC, in-repo content — NOT the substrate-sourced /thoughts rail. No
// substrate, no substrate-verify gate. To regenerate after editing a guide:
//     node scripts/compileGuides.mjs
// A test (tests/guidesBundle.test.ts) asserts the committed bundle matches a fresh
// compile, so an edit to the .md that forgets to regenerate fails CI.
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT_DIR = path.join(ROOT, 'content', 'guides');
const OUT_FILE = path.join(ROOT, 'constants.guides.generated.ts');

const FRONTMATTER_KEYS = ['title', 'slug', 'date', 'category', 'description', 'lead'];

// Parse the leading --- frontmatter --- block. Values may be double-quoted (the
// quotes are stripped); the title legitimately contains a colon, so we split on
// the FIRST colon only.
function parse(raw, file) {
  const clean = raw.charCodeAt(0) === 0xfeff ? raw.slice(1) : raw; // strip a UTF-8 BOM (some Windows editors add one)
  const m = clean.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) throw new Error(`${file}: missing or malformed frontmatter`);
  const [, fm, body] = m;
  const meta = {};
  for (const line of fm.split(/\r?\n/)) {
    const mm = line.match(/^([A-Za-z_]+):\s*(.*)$/);
    if (!mm) continue;
    let [, key, value] = mm;
    value = value.trim();
    // Strip matching surrounding quotes (double or single).
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    meta[key] = value;
  }
  for (const k of FRONTMATTER_KEYS) {
    if (!meta[k]) throw new Error(`${file}: frontmatter missing required key "${k}"`);
  }
  return {
    title: meta.title,
    slug: meta.slug,
    date: meta.date,
    category: meta.category,
    description: meta.description,
    lead: meta.lead,
    body: body.trim(),
  };
}

export async function compileGuides(dir = CONTENT_DIR) {
  const files = (await fs.readdir(dir)).filter((f) => f.endsWith('.md')).sort();
  const guides = [];
  for (const f of files) {
    const raw = await fs.readFile(path.join(dir, f), 'utf8');
    guides.push(parse(raw, f));
  }
  // Newest first, stable by slug for ties (deterministic output).
  guides.sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
  return guides;
}

export function renderBundle(guides) {
  const header =
    '// GENERATED FILE — do not edit by hand.\n' +
    '// Source: content/guides/*.md (frontmatter + markdown body).\n' +
    '// Regenerated by scripts/compileGuides.mjs:  node scripts/compileGuides.mjs\n' +
    '// Static, in-repo content (NOT substrate-sourced). See AGENTS.md.\n\n' +
    "import type { Guide } from './types';\n\n" +
    'export const GUIDES: Guide[] = ';
  // JSON.stringify => double-quoted, fully-escaped strings: backticks stay literal
  // and ${...} cannot interpolate in a double-quoted TS string. Valid TS as-is.
  return `${header}${JSON.stringify(guides, null, 2)};\n`;
}

async function main() {
  const guides = await compileGuides();
  await fs.writeFile(OUT_FILE, renderBundle(guides), 'utf8');
  console.log(`compileGuides: wrote ${guides.length} guide(s) -> ${path.relative(ROOT, OUT_FILE)}`);
  for (const g of guides) console.log(`  - ${g.slug} (${g.body.length} body chars)`);
}

// Run as CLI; stay importable for the drift test.
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
